# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

commands:
  install_dependencies:
    description: "Install required dependencies to run the test suite"
    steps:
      - checkout

      - run:
          name: install bundler
          command: |
            gem install bundler -v 2.0.2

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install gemfile dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: install node dependencies
          command: |
            yarn install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}

executors:
  acts_as_template-config:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: root
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_DB: acts_as_template_test
          POSTGRES_USER: root
    working_directory: ~/project

jobs:
  setup:
    executor: acts_as_template-config
    steps:
      - install_dependencies

  rspec:
    executor: acts_as_template-config
    steps:
      - install_dependencies
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb")"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec/results.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2.1
  acts_as_template:
    jobs:
      - setup
      - rspec:
          requires:
            - setup
